"""
Django settings for stech_main project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from datetime import timedelta
import pyodbc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-97o&+knmnla0dlpqqa3s_(-kxd(%x8#f@u2@d_holbr@jetu_n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'reporte.apps.ReporteConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'stech_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stech_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'DB_ST',
        'USER': 'STEC',
        'PASSWORD': 'sasa',
        'HOST': 'PC005',  # Cambia esto a la dirección de tu servidor SQL Server
        'PORT': '',           # Deja esto vacío para usar el puerto predeterminado
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # El nombre del controlador ODBC instalado
        },
    }
}

DATABASES["default"] = dj_database_url.parse("postgres://stech_user:qWpJGK45J65gDOC7xiTbCOBmQeCG6JRq@dpg-cnthkf20si5c73dob49g-a.oregon-postgres.render.com/stech")

# DATABASES = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'DB_ST',
#         # 'USER': 'tu_usuario',
#         # 'PASSWORD': 'tu_contraseña',
#         'Trusted_Connection': 'yes',  # Utiliza autenticación de Windows
#         'HOST': '192.168.18.78',
#         'PORT': '50260',  # Puedes dejarlo vacío si usas el puerto predeterminado
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Esto puede variar según tu versión de controlador
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),  # Duración del token de acceso (en este caso, 1 año)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),   # Duración del token de actualización (en este caso, 1 día)
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Origen de tu aplicación React
    'http://localhost:5000',
    'https://reporte-f-stech.onrender.com/',
    # Otros orígenes permitidos si los hay...
]