# Generated by Django 5.0.3 on 2024-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('CANAL', models.CharField(max_length=4000)),
                ('NUMERO_ORDEN', models.CharField(max_length=4000, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OC_ORDENES_CONS',
            },
        ),
    ]
