# Generated by Django 5.0.3 on 2024-03-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordenes',
            table='oc_ordenes_cons',
        ),
    ]
