# Generated by Django 5.0.3 on 2024-03-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_alter_ordenes_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='CANAL',
            new_name='canal',
        ),
        migrations.RenameField(
            model_name='ordenes',
            old_name='NUMERO_ORDEN',
            new_name='numero_orden',
        ),
    ]
