# Generated by Django 5.0.3 on 2024-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_rename_canal_ordenes_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='categoria_producto',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='codigo_producto_canal',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='direccion_cliente',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='dni_cliente',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='estado_orden',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_despacho',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_orden',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_proceso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='marca_producto',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='modelo_producto',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='nombre_cliente',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='nombre_producto',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='numero_factura',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='observacion_orden',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='part_number',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='precio_c_igv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='precio_s_igv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='region_venta',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='st_despacho',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='total_c_igv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='total_s_igv',
            field=models.FloatField(null=True),
        ),
    ]
