# Generated by Django 5.0.4 on 2024-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0004_ordenes_cantidad_ordenes_categoria_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasDiarias',
            fields=[
                ('dia', models.DateTimeField(primary_key=True, serialize=False)),
                ('total_soles_dia', models.FloatField(null=True)),
                ('total_unidades_dia', models.IntegerField(null=True)),
                ('total_soles_mes', models.FloatField(null=True)),
                ('total_unidades_mes', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'oc_ventas_mes_cons',
            },
        ),
    ]
