# Generated by Django 5.0.4 on 2024-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0005_ventasdiarias'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasCanales',
            fields=[
                ('canal', models.CharField(primary_key=True, serialize=False)),
                ('cantidad_ordenes', models.IntegerField(null=True)),
                ('cantidad_productos', models.IntegerField(null=True)),
                ('precio_s_igv', models.FloatField(null=True)),
                ('precio_c_igv', models.FloatField(null=True)),
                ('porcentaje', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'oc_ventas_canal_cons',
            },
        ),
        migrations.CreateModel(
            name='VentasProductos',
            fields=[
                ('marca_producto', models.CharField(primary_key=True, serialize=False)),
                ('mini_codigo', models.CharField(max_length=255, null=True)),
                ('part_number', models.CharField(max_length=255, null=True)),
                ('stock_restante', models.IntegerField(null=True)),
                ('cantidad_productos_vendidos', models.IntegerField(null=True)),
                ('subtotal_s_igv', models.FloatField(null=True)),
                ('total_c_igv', models.FloatField(null=True)),
                ('porcentaje', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'oc_ventas_productos_cons',
            },
        ),
    ]
